### ISSUE TITLE
Use redux to populate a table

### ISSUE THREAD

**Issue by MadalinNitu** [thaind97git/react-typescript-webpack#6]
Will be good an example for how to populate a table using redux with data from api-calls.

**Comment by thaind97git** [comment]
I think this is a feature out of the context of this repo. This repo is just a simple manual config webpack with typescript, not implement a dynamic feature.
Thanks for your suggestion, but I think I won't do it right now.

**Comment by MadalinNitu** [comment]
Thanks for you response. I consider this task done.
